services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - zookeeper
  event-service:
    build: .
    container_name: event-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - event_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event_db:5432/eventDB

  event_db:
    image: postgres:14.1-alpine
    container_name: event_db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: eventDB
    ports:
      - "5434:5432"
    volumes:
      - event_db_data:/var/lib/postgresql/data

volumes:
  event_db_data: