services:
  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - payment_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment_db:5432/paymentDB

  payment_db:
    image: postgres:14.1-alpine
    container_name: payment_db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: paymentDB
    ports:
      - "5435:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

volumes:
  payment_db_data: