services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2183:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9095:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - zookeeper
  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - payment_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment_db:5432/paymentDB

  payment_db:
    image: postgres:14.1-alpine
    container_name: payment_db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: paymentDB
    ports:
      - "5435:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

volumes:
  payment_db_data: