services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2182:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9093:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - zookeeper
  booking-service:
    build: .
    container_name: booking-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - booking_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://booking_db:5432/bookingDB

  booking_db:
    image: postgres:14.1-alpine
    container_name: booking_db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: bookingDB
    ports:
      - "5433:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data

volumes:
  booking_db_data: