services:
  booking-service:
    build: .
    container_name: booking-service
    ports:
      - "8083:8083"
    depends_on:
      - booking_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://booking_db:5432/bookingDB

  booking_db:
    image: postgres:14.1-alpine
    container_name: booking_db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: bookingDB
    ports:
      - "5433:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data

volumes:
  booking_db_data: